<?php

namespace AppBundle\Repository;

/**
 * PlantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantRepository extends \Doctrine\ORM\EntityRepository
{
}
