version: '2'
services:
  chloris_php:
    build: .
    hostname: "chloris_php"
    container_name: "chloris_php"
    volumes:
      - "../../:/var/www/chloris"
    networks:
      chloris_network:
        ipv4_address: 10.0.0.3
  chloris_mysql:
    image: "mysql:latest"
    hostname: "chloris_mysql"
    container_name: "chloris_mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "dev"
      MYSQL_DATABASE: "chloris"
    networks:
      chloris_network:
        ipv4_address: 10.0.0.2
  chloris_nginx:
    image: "nginx:alpine"
    hostname: "chloris_nginx"
    container_name: "chloris_nginx"
    ports:
      - "80:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "../../:/var/www/chloris"
    networks:
      chloris_network:
        ipv4_address: 10.0.0.1
networks:
  chloris_network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.0.0.0/28
         gateway: 10.0.0.14
