version: '3'
services:
  chloris_php:
    build: .
    hostname: "chloris_php"
    container_name: "chloris_php"
    volumes:
      - "../../:/var/www/chloris"
  chloris_mysql:
    image: "mysql:5.6"
    hostname: "chloris_mysql"
    container_name: "chloris_mysql"
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "dev"
      MYSQL_DATABASE: "chloris"
  chloris_nginx:
    image: "nginx:alpine"
    hostname: "chloris_nginx"
    container_name: "chloris_nginx"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.prod.conf"
      - "../../:/var/www/chloris"
    ports:
      - "80:80"
