version: '3'

services:

  chloris_php:
    build:
      context: .
      args:
        DOCKER_UID: $DOCKER_UID
    hostname: chloris_php
    container_name: chloris_php
    volumes:
      - ../../:/var/www/chloris

  chloris_mysql:
    image: mysql:5.6
    hostname: chloris_mysql
    container_name: chloris_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: chloris

  chloris_nginx:
    image: nginx:1.15.10-alpine
    hostname: chloris_nginx
    container_name: chloris_nginx
    volumes:
      - ./nginx-${APP_ENV}.conf:/etc/nginx/conf.d/default.conf
      - ../../:/var/www/chloris
    ports:
      - 80:80
