imports:
    - { resource: config_dev.yml }

parameters:
    locale: en

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
        enabled: true
        only_exceptions: false

web_profiler:
    toolbar: false
    intercept_redirects: true

swiftmailer:
    disable_delivery: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext
