<?php

namespace PlantBundle\Repository;

/**
 * PlantSpecificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantSpecificationRepository extends \Doctrine\ORM\EntityRepository
{
}
