#!/bin/bash

docker exec -i chloris_php "php bin/console cache:clear --no-warmup" &> /dev/null

( cd "${0%/*}/files" && docker-compose -f docker-compose-macos.yml down  )

( cd "${0%/*}/../app/config" && rm -f parameters.yml  )

printf "\033[1;34mDocker stopped\033[m\n"
